[general]

working_directory = "/home/marcelocra"
live_config_reload = true


[window]

# position = { x = 1303, y = 0 }
# dimensions = { columns = 126, lines = 50 }
# decorations = "None"
opacity = 0.95
blur = true
padding = { x = 3, y = 3 }
dynamic_padding = true


[scrolling]

history = 100000


[font]

# normal = { family = "Reddit Mono", style = "Regular" }
normal = { family = "MesloLGM Nerd Font", style = "Regular" }
size = 11


[colors]

# cursor = { text = "#000000", cursor = "#ff4500" }


[cursor]

style = { shape = "Beam" }
thickness = 0.2


[terminal]

shell = { program = "/usr/bin/xdotool", args = ["key", "Super+Right"] }
