[general]

working_directory = "/home/marcelocra"
live_config_reload = true


[window]

# position = { x = 1303, y = 0 }
# dimensions = { columns = 126, lines = 50 }
# decorations = "None"
opacity = 0.95
blur = true
padding = { x = 3, y = 3 }
dynamic_padding = true


[scrolling]

history = 100000


[font]

# normal = { family = "Reddit Mono", style = "Regular" }
normal = { family = "MesloLGM Nerd Font", style = "Regular" }
size = 11


[colors]

# cursor = { text = "#000000", cursor = "#ff4500" }


[cursor]

style = { shape = "Beam" }
thickness = 0.2


[terminal]

shell = { program = "/usr/bin/xdotool", args = ["key", "Super+Right"] }


[[hints.enabled]]

command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"


[keyboard]

bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "L", mods = "Control|Shift", chars = "l" },
]
