################################################################################
## More information in the configuration website:                             ##
##   https://alacritty.org/config-alacritty.html                              ##
################################################################################
# [my-themes]
# base_dir = "~/.config/alacritty/alacritty-theme/themes"
# [my-themes.light]
# best = "~/.config/alacritty/alacritty-theme/themes/catppuccin_latte.toml"
# good = [
#   "~/.config/alacritty/alacritty-theme/themes/dawnfox.toml",
#   "~/.config/alacritty/alacritty-theme/themes/dayfox.toml",
#   "~/.config/alacritty/alacritty-theme/themes/github_light.toml",
#   "~/.config/alacritty/alacritty-theme/themes/one_light.toml",
# ]
# to_try = []

# [my-themes.dark]
# best = "~/.config/alacritty/alacritty-theme/themes/cyber_punk_neon.toml"
# good = []
# to_try = [
#   "~/.config/alacritty/alacritty-theme/themes/catppuccin.toml",
#   "~/.config/alacritty/alacritty-theme/themes/catppuccin_frappe.toml",
#   "~/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml",
#   "~/.config/alacritty/alacritty-theme/themes/catppuccin_macchiato.toml",
#   "~/.config/alacritty/alacritty-theme/themes/monokai.toml",
#   "~/.config/alacritty/alacritty-theme/themes/monokai_charcoal.toml",
# ]

################################################################################
[general]
################################################################################
working_directory = "/home/marcelocra"
live_config_reload = true

import = [
  "~/.config/alacritty/alacritty-theme/themes/cyber_punk_neon.toml",
  "~/.config/alacritty/alacritty-theme/themes/catppuccin_latte.toml",
]

################################################################################
[font]
################################################################################
# 7 or 8 are the minimum that are still readable, depending on the font. Very
# small for my taste, though. The minimum that I find comfortable are 9 or 10.
size = 11.0

[font.normal]
style = "Regular"

# Organized by height. This is not very precise, as some fonts have the same
# height in some sizes but not in others.
# --- Smaller ---
# family = "CodeNewRoman Nerd Font" # 9+
# family = "Iosevka Nerd Font" # min: 10, good: 12
family = "IosevkaTermSlab Nerd Font" # min: 10, good: 12
# family = "Hack Nerd Font" # min: 8, good: 9+
# family = "RecMonoLinear Nerd Font"
# family = "RecMonoDuotone Nerd Font"
# family = "M PLUS 1 Code"
# --- Small ---
# family = "SourceCodeVF"
# family = "MesloLGS Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "BlexMono Nerd Font" # Lighter.
# --- Medium ---
# family = "MesloLGM Nerd Font"
# family = "Noto Sans Mono"
# family = "Red Hat Mono"
# family = "Reddit Mono"
# --- Large ---
# family = "MesloLGL Nerd Font"
# --- New and unchecked below ---

[font.italic]
style = "Italic"

# family = "Monaspace Radon Var"
# family = "Blex Mono Nerd Font"
# family = "SourceCodeVF"
# family = "Iosevka Nerd Font"

################################################################################
[window]
################################################################################
position = { x = 1303, y = 0 }
decorations = "None"
opacity = 0.95                 # 0.93 is another good value to try.
blur = true
padding = { x = 4, y = 1 }     # Good value.
# padding = { x = 150, y = 130 }
# padding = { x = 20, y = 9 }
# padding = { x = 400, y = 1 }
dynamic_padding = true

[window.dimensions]
lines = 100 # Fills the whole height for all fonts.
# columns = 157 # Reddit|CodeNewRoman 11
columns = 139 # MesloM|Hack|JB 11

################################################################################
[scrolling]
################################################################################
history = 100000

################################################################################
[colors]
################################################################################
# cursor = { text = "#000000", cursor = "#ff4500" }
# draw_bold_text_with_bright_colors = false
# transparent_background_colors = true

# Using imported colors from the alacritty/alacritty-themes repo. Use the ones
# here only as a backup, if necessary.
#
# [colors.line_indicator]
#
# foreground = "#00ffff"
#
# [colors.primary]
#
# # Light.
# # foreground = "#000000"
# # background = "#ffffff"
#
# # Dark.
# foreground = "#e9e9e9"
# background = "#171f2c"

################################################################################
[cursor]
################################################################################
thickness = 0.3

[cursor.style]
shape = "Beam"

################################################################################
[terminal.shell]
################################################################################
program = "/usr/bin/xdotool"
args = ["key", "Super+Right"]

################################################################################
[[hints.enabled]]
################################################################################
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

################################################################################
[keyboard]
################################################################################
bindings = [
  { key = "V", mods = "Control|Alt", action = "ToggleViMode" },
  { key = "L", mods = "Control|Shift", chars = "l" },
]
