[general]

working_directory = "/home/marcelocra"
live_config_reload = true


[font]

normal = { family = "MesloLGS Nerd Font", style = "Regular" }
# normal = { family = "MesloLGM Nerd Font", style = "Regular" }
# normal = { family = "Reddit Mono", style = "Regular" }
# normal = { family = "Hack Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
# normal = { family = "CodeNewRoman Nerd Font Mono", style = "Regular" }
size = 11


[window]

# dimensions = { columns = 157, lines = 100 } # Reddit|CodeNewRoman 11
dimensions = { columns = 139, lines = 100 }   # MesloM|Hack|JB 11

position = { x = 1303, y = 0 }
decorations = "None"
opacity = 0.97  # 0.93 is another good value to try.
blur = true
padding = { x = 3, y = 3 }
dynamic_padding = true


[scrolling]

history = 100000


[colors]

# cursor = { text = "#000000", cursor = "#ff4500" }
transparent_background_colors = true


[cursor]

style = { shape = "Beam" }
thickness = 0.3


[terminal]

shell = { program = "/usr/bin/xdotool", args = ["key", "Super+Right"] }


[[hints.enabled]]

command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"


[keyboard]

bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "L", mods = "Control|Shift", chars = "l" },
]
