#!/usr/bin/env bash

set -euo pipefail  # Exit on errors.

export DOTFILES_SKIP_HOMEBREW="${DOTFILES_SKIP_HOMEBREW:-false}"
export DOTFILES_SKIP_CLI_TOOLS="${DOTFILES_SKIP_CLI_TOOLS:-false}"
export DOTFILES_SKIP_ZSH_PLUGINS="${DOTFILES_SKIP_ZSH_PLUGINS:-false}"
export DOTFILES_SKIP_VSCODE"${DOTFILES_SKIP_VSCODE:-true}"
export DOTFILES_SKIP_EDITOR_LAUNCHER"${DOTFILES_SKIP_EDITOR_LAUNCHER:-true}"
export DOTFILES_SKIP_GIT_SHIMS="${DOTFILES_SKIP_GIT_SHIMS:-false}"
export DOTFILES_SKIP_SSH_CONFIG="${DOTFILES_SKIP_SSH_CONFIG:-false}"
export DOTFILES_DIR="$HOME/x/dotfiles"
export DOTFILES_DEBUG="1"

./shell/install.sh
