" vim:fdm=marker:fmr={{{,}}}:fdl=0:fen:ai:et:ts=2:sw=2:tw=80:ff=unix:fenc=utf8:et:fixeol:eol:
"
" Common settings that should work both in Vim and Neovim should be here.
"
" Neovim-only stuff should be in the `neovim.*` files.

" Easily source my vimrc. I like it folded by default, so run za after sourcing,
" to reopen the file exactly where I was.
inoremap <leader><leader>sv <esc>:w<cr>:source $MYVIMRC<cr>zazza
nnoremap <leader><leader>sv :source $MYVIMRC<cr>zazz

" Easily edit my vimrc.
nnoremap <leader><leader>ev :vspl $MYVIMRC<cr>
nnoremap <leader><leader>etv :tabe $MYVIMRC<cr>

" Keep this at the end!
call _mcra_debug("vimrc loaded!")

